retriever_task:
  description: >
    Analyse the contents of {topic} and identify unique website URLS
    within, and returning every single one was they appeared
    in the order that they appeared, without duplicate domains

  expected_output: >
    The unique, correct URLS of the websites in {topic}
    In a well formatted manner and in the order of which they appeared.
    Each URL should also have a unique domain. No two URLS should
    share the same domain, this is mandatory
  agent: retriever

mentor_task: 
  description: >
   Conduct a thorough scrape of all websites from a list of given URLs using
   provided tools,Analyse Compare and contrast the content from the differing websites,
   noting parallels and differences in order to
   formulate a comprehensive, well-formatted and easy to understand
   tutorial based on {query}. 
   
   If any data was quoted directly, the website 
   that it came from must be referenced. At the end, the URLS of all
   websites where the data originated from must be referenced.
   
   when scraping the websites, these guidelines MUST be followed:

   1). All Metadata should be ignored

   2). ALL website content should be analysed,
       regardless of length or relevance to the search query. 
       this is a requirement (except metadata). A different agent
       will interpret the output anyway

   3). avoid any use of asterisks (*) in the output, this is of utmost priority

   4) .If a website is inaccessible, completely ignore it and move
       onto the next one in the list
     
   5). At the end of the final output, state all URS visited and which ones
       were successfully scraped and which ones
       returned errors (if any)
    
  expected_output: >
   A well-written, fluid and comprehensive tutorial on {query} 
   using the input data as source material. the tutorial should be named
   "{query} - Tutorial". Any quoted material from the provided website scraped content
   should be referenced.
   The URLS of ALL websites where each scraped content was sourced from should be listed at the end
   
  agent: mentor